server:
  port: 8082 #服务端口

spring: 
  application:  
    name: springcloud-item #指定服务名

eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://eureka:123@127.0.0.1:6868/eureka/
  instance: 
    prefer-ip-address: true #将自己的ip地址注册到Eureka服务中
    ip-address: 127.1.1.2 #在实际应用中有时需要指定服务的IP地址
    
management:
  security:
    enabled: false #是否开启actuator安全认证

