server:
  port: 8181 #服务端口

spring: 
  application:  
    name: springcloud-order #指定服务名

eureka:
  client:
    registerWithEureka: false #是否将自己注册到Eureka服务中，默认为true
    fetchRegistry: true #是否从Eureka中获取注册信息，默认为true
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://eureka:123@127.0.0.1:6868/eureka/
           
springcloud-item:
   ribbon:
     NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
