server:
  port: 6868 #服务端口
  
spring: 
  application:  
    name: springcloud-eureka #指定服务名
  
eureka:
  client:
    registerWithEureka: false #是否将自己注册到Eureka服务中，本身就是所有无需注册，如果eureka集群的话，需要之间相互注册，此时设置为true
    fetchRegistry: false #是否从Eureka中获取注册信息
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:${server.port}/eureka/

security:
  basic:
    enabled: true #开启基于HTTP basic的认证
  user:  #配置用户的账号信息
     name: eureka
     password: 123